# Generated by Django 4.2.27 on 2026-04-13 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("amazon", "Amazon"),
                            ("flipkart", "Flipkart"),
                            ("croma", "Croma"),
                            ("reliance", "Reliance Digital"),
                        ],
                        max_length=40,
                    ),
                ),
                ("platform_product_id", models.CharField(blank=True, max_length=150)),
                ("title", models.CharField(max_length=300)),
                ("buy_url", models.URLField()),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("in_stock", models.BooleanField(default=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="core.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("in_stock", models.BooleanField(default=True)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="core.productlisting",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["platform", "fetched_at"], name="core_produc_platfor_443140_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productlisting",
            unique_together={("product", "platform")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["captured_at"], name="core_priceh_capture_78e3f1_idx"
            ),
        ),
    ]
